AWSTemplateFormatVersion: 2010-09-09
Description: ND9991 C3 L4 

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 3rdk
      ImageId: ami-08c40ec9ead489470
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2SecGroup

  EC2SecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0