---
  - name: update apt-package
    become: true
    apt: 
      update_cache: true

  - name: upgarde apt packages
    become: true
    apt: 
      upgrade: true

  - name: install node npm
    become: true
    apt: 
      name: ["nodejs", "npm"] 
      state: latest


  - name: install pm2
    npm:
      name: pm2
      global: yes

  - name: create directory
    file: 
      path: ~/web
      state: directory

  - name: copy file
    copy: 
      src: index.js
      dest: ~/web/index.js

  - name: start webpage
    shell: pm2 start ~/web/index.js -f 